name: 'pretix-plugin-dev'
services:
  database:
    image: postgres:14
    environment: 
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=pretix

  redis:
    image: redis:latest

  pretix:
    build:
      context: .
      dockerfile: .docker-dev/Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - ${PRETIX_PORT:-8002:8000}
    volumes:
      - .docker-dev/pretix.cfg:/etc/pretix/pretix.cfg
      - .:/plugins/
      - ./rootfs/data:/data
      #- ./rootfs/src:/pretix/src

  #####
  # Mailpit (local smtp)
  mailpit:
    image: axllent/mailpit:latest
    hostname: mailpit
    ports:
      - ${MAILPIT_PORT:-8025:8025}