version: '3'
services:
  database:
    image: postgres:14
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=pretix

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  pretix:
    build:
      context: .
      dockerfile: .docker-dev/Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .docker-dev/pretix.cfg:/etc/pretix/pretix.cfg
      - .:/pretix-custom-js
      - ./rootfs/data:/data
      #- ./rootfs/src:/pretix/src

